# Generated by Django 4.2.23 on 2025-07-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/'),
        ),
    ]
