# Generated by Django 4.2.23 on 2025-08-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lmode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='plang',
            field=models.CharField(default='en', max_length=100),
        ),
    ]
