# Generated by Django 4.2.23 on 2025-08-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_lmode_user_plang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plang',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ru', 'Russian')], default='en', max_length=10),
        ),
    ]
